name: Update JagoBD IPTV Playlist

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 */2 * * *'  # Run every 2 hours

jobs:
  update-playlist:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run JagoBD playlist generator
      run: python generate_playlist.py
      
    - name: Commit and push if changed
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add playlist.m3u
        git diff --quiet && git diff --staged --quiet || git commit -m "Auto-update JagoBD playlist - $(date +'%Y-%m-%d %H:%M')"
        git push
